local ITEM = Clockwork.item:New("weapon_base");
	ITEM.name = "Бита";
	ITEM.model = "models/weapons/tfa_nmrih/w_me_bat_metal.mdl";
	ITEM.weight = 0.9;
	ITEM.uniqueID = "tfa_nmrih_bat";
	ITEM.isMeleeWeapon = true;
	ITEM.category = "Оружие";
	ITEM.description = "";
	ITEM.isAttachment = true;
	ITEM.attachmentBone = "ValveBiped.Bip01_Spine1";
	ITEM.attachmentOffsetAngles = Angle(360, 90, -10);
	ITEM.attachmentOffsetVector = Vector(-6, 3, 8);
ITEM:Register();